package:
  name: melange-apko-test
  version: 0.1.0
  description: Test project for melange + apko builds
  target-architecture:
    - all
  copyright:
    - license: UNLICENSED
      paths:
        - '*'
  dependencies:
    runtime:
      - nodejs
      - npm
      - tailscale

environment:
  contents:
    repositories:
      - https://dl-cdn.alpinelinux.org/alpine/edge/main
      - https://dl-cdn.alpinelinux.org/alpine/edge/community
    packages:
      - alpine-baselayout-data
      - ca-certificates-bundle
      - busybox
      - nodejs
      - npm
      
      # for node packages with native dependencies
      # - make
      # - python3
      # - gcc

      # secure networking
      - tailscale

pipeline:
  - name: Build Node application
    runs: |
      # export npm_config_cache=/work/.npm
      # npm i -g pnpm
      EXECDIR="${{targets.destdir}}/usr/bin"
      WEBAPPDIR="${{targets.destdir}}/usr/share/webapps/${{package.name}}"
      mkdir -p "${EXECDIR}" "${WEBAPPDIR}"

      # pnpm install --prod
      # pnpm build
      npm install --no-bin-links --omit=dev
      ./node_modules/next/dist/bin/next build
      cp package.json "${WEBAPPDIR}"
      cp pnpm-lock.yaml "${WEBAPPDIR}"
      cp -r node_modules "${WEBAPPDIR}"
      cp -r .next "${WEBAPPDIR}"
      cp -r public "${WEBAPPDIR}"

      echo "#!/bin/sh" >> "${EXECDIR}/${{package.name}}"
      # echo "pnpm start" >> "${EXECDIR}/${{package.name}}"
      echo "cd /usr/share/webapps/${{package.name}} && ./node_modules/next/dist/bin/next start" >> "${EXECDIR}/${{package.name}}"
      chmod +x "${EXECDIR}/${{package.name}}"


